### ISSUE TITLE
Free practice !!

### ISSUE THREAD

**Issue by Racing-France** [cazzoo/RFChampionship#28]
Reporter : //RF//Jabber
Results in Free practice don't work, you can't set them!!!!!

**Comment by cazzoo** [comment]
Cette anomalie est une anomalie de design. Il a été convenu qu'on ne pouvait pas attribuer de résultats aux essais libres. Doit-on revenir en arrière et autoriser l'attribution de pilotes aux règles?

**Comment by cazzoo** [comment]
Pas de retour sur cette anomalie => clôture
