### ISSUE TITLE
système points

### ISSUE THREAD

**Issue by Racing-France** [cazzoo/RFChampionship#29]
Reporter : //RF//alexh2o
Je soulève un problème au niveau du système de points, le tour le plus rapide apparaît en milieu de tableau.

**Comment by cazzoo** [comment]
Cette anomalie est une anomalie de design. A quel endroit la règles doit être apparaitre? Doit-on prévoir de placer certaines règles dans un ordre précis?

**Comment by cazzoo** [comment]
Pas de retour sur cette anomalie => clôture
