### ISSUE TITLE
Pictures

### ISSUE THREAD

**Issue by Racing-France** [cazzoo/RFChampionship#33]
Reporter : //RF//MotorSport
Les images des manches dans le championnat GR5 ne s'affiche pas.

http://championships.racing-france.fr/images/wireframe/image.png
Oops! An Error Occurred
The server returned a "404 Not Found".
Something is broken. Please let us know what you were doing when this error occurred. We will fix it as soon as possible. Sorry for any inconvenience caused.

**Comment by cazzoo** [comment]
La gestion des images n'a été que partiellement implémentée.
Le fix est prévu plus tard

**Comment by cazzoo** [comment]
Les galeries sont maintenant implémentées et fonctionnent.
